### ISSUE TITLE
model

### ISSUE THREAD

**Issue by wudami** [yayoyo66/SRStitcher#3]
Hello, where should I download the model stable-diffusion-2-inpainting used?

**Comment by wudami** [comment]
![33](https://github.com/yayoyo66/SRStitcher/assets/154413680/14a932f8-558c-4fad-8e4e-fd95f7f7dc35)
Do I need to download all the files here?https://hf-mirror.com/stabilityai/stable-diffusion-2-inpainting/tree/main

**Comment by yayoyo66** [comment]
You don't need to download it manually. running the code it will download automatically

**Comment by wudami** [comment]
> You don't need to download it manually. running the code it will download automatically

Thank you very much for your answer.
